const issues = [
  {
    id: "ferrofluid-obsidian",
    src: "images/erun_issue_ferrofluid_obsidian_velvet_3x4.jpg",
    title: "Ferrofluid Magnetic Sculpture & Obsidian Velvet",
    collection: "Issue 34 — Magnetic Alchemy",
    pillar: "New Concepts",
    tag: "NEW · 2026-08-06",
    palette: "#1A1A1A",
    masthead: "Obsidian Grey",
    prompt: "Groundbreaking high-fashion cover for E-RUN Magazine. Obsidian-black velvet column dress with copper induction embroidery, minimalist concrete lab with magnetic coils on basalt floors, living black ferrofluid forming spiky geometric crowns around neckline & wrists. Hasselblad H6D-100c — speculative physics luxury.",
    hook: "When magnetic fields turn liquid iron into razor-sharp geometric sculpture. 🧲⚫",
    story: "Composed of nanoscale ferromagnetic particles in organic carrier oil, this liquid metal morphs from smooth ribbons into dramatic spiky crowns the instant our hidden coils activate. Your neckline adapts from soft elegance to formidable spikes at the flick of a switch.",
    cta: "Fluid Ribbons or Sharp Spikes?",
    hashtags: "#ERUNMagazine #FerrofluidFashion #MagneticCouture #ObsidianVelvet #DarkLuxury"
  },
  {
    id: "gothic-wheelchair-mask",
    src: "images/erun_issue_gothic_wheelchair_mask_3x4.jpg",
    title: "Gothic Wheelchair Mask — Sovereign Noir",
    collection: "Collection 11 — Gothic Velvet Luxury",
    pillar: "Gothic Luxury",
    tag: "FEATURED · Gothic",
    palette: "#5B061A",
    masthead: "Deep Gothic Burgundy",
    prompt: "Aristocratic dark luxury editorial. Model in deep burgundy velvet gown seated in ornate wheelchair, wearing sculpted obsidian mask with iridescent filigree, chiaroscuro lighting, marble hall, neo-gothic regal mood — E-RUN masthead distressed burgundy.",
    hook: "True power doesn't need to stand to command the room. 🖤♿️👑",
    story: "Shot in the marble sanctuaries of Sector 3, where permanence is luxury. The obsidian mask is forged from hand-pressed velvet composite and hand-painted iridescence — armor for those who rule quietly.",
    cta: "What does sovereign beauty mean to you?",
    hashtags: "#ERUNMagazine #GothicLuxury #InclusiveFashion #SovereignStyle #DarkElegance"
  },
  {
    id: "jellyfish-chrome",
    src: "images/erun_issue_jellyfish_chrome.jpg",
    title: "The Abyssal Circus — Jellyfish Chrome",
    collection: "Collection 01 — Deep-Sea Circus",
    pillar: "Cyber-Elegance",
    tag: "Issue 04",
    palette: "#00FFCC",
    masthead: "Neon Cyan",
    prompt: "Silver liquid-chrome high-neck bodysuit surrounded by glowing translucent cyan jellyfish floating mid-air inside dark circus tent with vertical ropes — cyan E-RUN header, Hasselblad, bioluminescent deep-sea cyber-elegance.",
    hook: "What happens when deep-sea bioluminescence meets digital haute couture? 🪼✨",
    story: "Inside pressurized floating domes of Sector 9, living jellyfish pulse in hydro-gel pockets, their cyan light mirrored by chromium fabric in a synchronized dance.",
    cta: "Would you attend a floating zero-gravity runway? Drop a 🪼!",
    hashtags: "#ERUNMagazine #DeepSeaFashion #BioluminescentCouture #JellyfishAesthetic"
  },
  {
    id: "kintsugi-swans",
    src: "images/erun_issue_kintsugi_swans.jpg",
    title: "Kintsugi Swans — Golden Scars",
    collection: "Collection 12 — Kintsugi & Solarpunk",
    pillar: "Bio-Futurism",
    tag: "Issue 26",
    palette: "#D4AF37",
    masthead: "Classic Serif White",
    prompt: "Ethereal white tulle crystal gown seated on submerged chair in turquoise tiled pool with white swans bearing kintsugi gold cracks — dreamlike luxury fashion photography.",
    hook: "Broken and mended with pure gold. 🦢✨",
    story: "Kintsugi philosophy brought to life: porcelain-feathered swans traced in 24-karat gold leaf surround weightless tulle — fractures gilded as history.",
    cta: "What scar made you more precious?",
    hashtags: "#ERUNMagazine #KintsugiArt #SwanLakeFuturism #GoldenResilience"
  },
  {
    id: "liquid-rainbow-beauty",
    src: "images/erun_issue_liquid_rainbow_beauty.jpg",
    title: "Liquid Rainbow — Holographic Chrome Beauty",
    collection: "Collection 12 — Liquid Chrome Beauty",
    pillar: "Digital Surrealism",
    tag: "Issue 26",
    palette: "#A855F7",
    masthead: "Iridescent Prism",
    prompt: "Ultra close-up holographic liquid chrome face portrait with rainbow prism refraction splitting across cheekbones — optical physics beauty editorial.",
    hook: "Wear pure optical refraction as makeup. 🌈🔍",
    story: "Photonic prism arrays project spectral bands onto skin — every movement paints an evolving geometry of light. In 2088, the face is a canvas for physics.",
    cta: "Tag a photographer who needs prism refraction!",
    hashtags: "#ERUNMagazine #PrismPhotography #HolographicBeauty #LiquidChrome"
  },
  {
    id: "crystal-butterfly-gaze",
    src: "images/erun_issue_crystal_butterfly_gaze_3x4.jpg",
    title: "Crystal Butterfly Gaze",
    collection: "Collection 08 — Crystalline Ice",
    pillar: "Cyber-Elegance",
    tag: "Issue 18",
    palette: "#AEEBFF",
    masthead: "Glacial Ice Blocks",
    prompt: "Cryogenic surrealism — model with icy blue lips encased in glowing stacked horizontal blocks of glacial crystal like architectural steps, frozen masthead text illuminated.",
    hook: "Frozen in time. Engineered from pure glacial crystal. 🧊❄️",
    story: "Thermal-stabilized hyper-ice blocks float with millimeter precision via electromagnetic stasis — architecture you wear.",
    cta: "What would you preserve in ice forever?",
    hashtags: "#ERUNMagazine #CryoFashion #IceArchitecture #GlacialElegance"
  },
  {
    id: "afterglow-flash",
    src: "images/erun_issue_afterglow_flash_3x4.jpg",
    title: "Afterglow Flash — Thermal Bloom",
    collection: "Collection 10 — Prism Refraction",
    pillar: "Digital Surrealism",
    tag: "Issue 22",
    palette: "#FF6B35",
    masthead: "Thermal Orange",
    prompt: "Model with sliced rainbow prism rays across face, clean studio, high contrast shadows, optical prism laboratory fashion.",
    hook: "Afterglow caught on thermal film. 🔥📸",
    story: "Infrared botanical portraiture meets prism physics — orange leaf veins echo heat signatures projected onto skin.",
    cta: "Which spectrum suits you: violet or amber?",
    hashtags: "#ERUNMagazine #ThermalFashion #PrismLight #Ultraviolet"
  },
  {
    id: "albino-coral-mohawk",
    src: "images/erun_issue_albino_coral_mohawk_3x4.jpg",
    title: "Albino Coral Mohawk — Xenobotany",
    collection: "Collection 05 — Xenobotanical",
    pillar: "Bio-Futurism",
    tag: "Issue 12",
    palette: "#FFD6E7",
    masthead: "Coral Pink",
    prompt: "Sculptural headpiece of ribbed albino coral and bone branching into mohawk, matching pale knit, emerald background — xenobotanical marine surrealism.",
    hook: "When coral becomes couture. 🪸💗",
    story: "Memory-shape elastane mimics cephalopod musculature — knitting that coils and relaxes with humidity.",
    cta: "Would you wear a sculptural headpiece to gala?",
    hashtags: "#ERUNMagazine #Xenobotany #CoralCouture #MarineSurrealism"
  },
  {
    id: "biosynthetic-pearls-3x4",
    src: "images/erun_issue_biosynthetic_pearls_3x4.jpg",
    title: "Biosynthetic Pearls — Amniotic Couture",
    collection: "Collection 05 — Xenobotanical",
    pillar: "Bio-Futurism",
    tag: "Issue 12",
    palette: "#F5F1E8",
    masthead: "Pearlescent White",
    prompt: "Model enraptured in translucent amniotic membranes and giant biosynthetic pearls — pearl-diver future, opalescent studio lighting.",
    hook: "Born from engineered mother-of-pearl. 🤍🦪",
    story: "Lab-grown pearlescent membranes pulse like living organism — jewelry that breathes.",
    cta: "Pearls fluid or pearls structured?",
    hashtags: "#ERUNMagazine #BiosyntheticPearls #AmnioticFashion #OrganicFuturism"
  },
  {
    id: "black-rose-blindfold",
    src: "images/erun_issue_black_rose_blindfold.jpg",
    title: "Black Rose Blindfold — Gothic Devotion",
    collection: "Collection 11 — Gothic Velvet",
    pillar: "Gothic Luxury",
    tag: "Issue 24",
    palette: "#0A0A0A",
    masthead: "Gothic Burgundy",
    prompt: "Model with black rose petal blindfold, deep burgundy velvet, marble and chiaroscuro — sovereign dark.",
    hook: "Seeing without eyes. 🌹🖤",
    story: "In the estate sanctuaries, sight is a choice — petals replace vision, velvet replaces armor.",
    cta: "What would you see if you closed your eyes?",
    hashtags: "#ERUNMagazine #GothicVelvet #BlackRose #SovereignDark"
  },
  {
    id: "brutalist-runes",
    src: "images/erun_issue_brutalist_runes_3x4.jpg",
    title: "Brutalist Runes — Concrete Liturgy",
    collection: "Collection 06 — Neo-Brutalist",
    pillar: "Neo-Brutalist",
    tag: "Issue 14",
    palette: "#7A7A7A",
    masthead: "Neon Yellow",
    prompt: "Triple mirror reflection in dark industrial corridor — deconstructed black techwear trench, heavy boots, angled mirrors creating infinite echo.",
    hook: "In the hall of mirrors, every angle reveals new armor. 🖤🏙️",
    story: "Radar-absorbent matte wool and asymmetrical holsters for urban evasion — coat as sanctuary.",
    cta: "Tag your favorite darkwear brand!",
    hashtags: "#ERUNMagazine #Techwear #NeoBrutalist #Darkwear"
  },
  {
    id: "cyber-goth-biomech-tail",
    src: "images/erun_issue_cyber_goth_biomech_tail_3x4.jpg",
    title: "Cyber-Goth Biomech Tail — Neon Subculture",
    collection: "Collection 13 — Cyber-Goth",
    pillar: "Neo-Brutalist",
    tag: "Issue 28",
    palette: "#FF00A0",
    masthead: "Neon Pink",
    prompt: "Black latex bunny ears, corset, glowing neon koi and sakura subdermal tattoos, biomechanical tail — neo-Tokyo night market.",
    hook: "When skin becomes a programmable neon display. 🏮🐰",
    story: "Sub-dermal OLED luminescence animates koi across collarbones — petal fall in real time.",
    cta: "What glowing tattoo would you choose?",
    hashtags: "#ERUNMagazine #CyberGoth #NeonTattoos #NeoTokyo"
  },
  {
    id: "ice-crystal-skull",
    src: "images/erun_issue_ice_crystal_skull.jpg",
    title: "Ice Crystal Skull — Cryo Crown",
    collection: "Collection 08 — Crystalline Ice",
    pillar: "Cyber-Elegance",
    tag: "Issue 18",
    palette: "#E0F7FF",
    masthead: "Frozen Ice",
    prompt: "Model with translucent ice-crystal skull crown refracting lavender mist — cryo-luxury atrium.",
    hook: "Crown forged from frozen light. 👑🧊",
    story: "Zero-gravity ice architecture holds light captive — each facet a frozen photon.",
    cta: "Ice or chrome crown?",
    hashtags: "#ERUNMagazine #IceCrown #CryoLuxury #FrozenLight"
  },
  {
    id: "lionheart-armory",
    src: "images/erun_issue_lionheart_armory_3x4.jpg",
    title: "Lionheart Armory — Gilded Guard",
    collection: "Collection 14 — Imperial Neo-Baroque",
    pillar: "Gothic Luxury",
    tag: "Issue 30",
    palette: "#C5A253",
    masthead: "Gold Filigree",
    prompt: "Royal neo-baroque model with ornate wire gold filigree crown and sapphire drops, royal blue satin gown with gold embroidery — imperial futurism.",
    hook: "Royalty in 2088 is engineered. 👑✨",
    story: "Each suspended gem is neural memory crystal — dynasty archives worn on the brow.",
    cta: "Who deserves a golden crown today?",
    hashtags: "#ERUNMagazine #NeoBaroque #ImperialStyle #GoldAndSapphire"
  },
  {
    id: "obsidian-mask-iridescent",
    src: "images/erun_issue_obsidian_mask_iridescent.jpg",
    title: "Obsidian Mask — Iridescent Prism",
    collection: "Collection 07 — Holographic Chrome",
    pillar: "Digital Surrealism",
    tag: "Issue 16",
    palette: "#A855F7",
    masthead: "Iridescent 3D",
    prompt: "Cyborg model with opaque red LED visor and rainbow liquid chrome armor, glowing glass tentacles radiating — royal electric blue, holographic luxury.",
    hook: "Why wear fabric when you can wear radiating light? 🌈⚡",
    story: "Fiber-optic heat sinks project holographic auroras — you become the sector's brightest source.",
    cta: "Rate this exoskeleton 1-10!",
    hashtags: "#ERUNMagazine #LiquidChrome #HolographicArmor #CyborgQueen"
  },
  {
    id: "molten-amber-devotion",
    src: "images/erun_issue_molten_amber_devotion.jpg",
    title: "Molten Amber Devotion — Chronolithic",
    collection: "Collection 12 — Chronolithic Amber",
    pillar: "Bio-Futurism",
    tag: "Issue 35",
    palette: "#FF8C00",
    masthead: "Saffron Gold",
    prompt: "Strapless gown of flexible clear resin and fossilized golden amber panels encasing alien orchids and golden spores — sun-drenched atrium.",
    hook: "Captured in amber for 10,000 years. ⏳🌼",
    story: "Flexible bio-resin fossilizes xenobotanical orchids — wearable geological archive that outlives you.",
    cta: "What flower would you preserve for eternity?",
    hashtags: "#ERUNMagazine #ChronolithicFashion #AmberCouture #DeepTime"
  },
  {
    id: "silk-katana-reverie",
    src: "images/erun_issue_silk_katana_reverie_3x4.jpg",
    title: "Silk Katana Reverie",
    collection: "Collection 04 — Cyber-Angel",
    pillar: "Cyber-Elegance",
    tag: "Issue 11",
    palette: "#C9B6FF",
    masthead: "Pristine White",
    prompt: "Model in studded lavender two-piece with chrome blue mechanical angel wings wielding polished futuristic greatsword — royal blue backdrop, high-octane fantasy.",
    hook: "Angelic silhouettes forged from titanium. ⚔️🪽",
    story: "Carbon-nanotube artificial muscles expand 7-foot cobalt wings on instinct — couture that protects.",
    cta: "Wings or greatsword?",
    hashtags: "#ERUNMagazine #CyberFantasy #MechanicalWings #CelestialSteel"
  },
  {
    id: "twilight-motion-noir",
    src: "images/erun_issue_twilight_motion_noir_3x4.jpg",
    title: "Twilight Motion Noir — Analog Future",
    collection: "Collection 06 — Neo-Brutalist",
    pillar: "Neo-Brutalist",
    tag: "Issue 14",
    palette: "#1F1F1F",
    masthead: "Mediterranean Analog",
    prompt: "Model in motion blur noir trench on wet concrete, Mediterranean analog grain, dusk neon reflections — Leica 35mm chiaroscuro.",
    hook: "Silence, snow, and modular efficiency at 10,000 ft. 🏔️⚪",
    story: "Aerogel insulation inside ripstop sailcloth for Vault 09 whiteouts — when nature turns monochrome, so must armor.",
    cta: "All-black or all-white techwear?",
    hashtags: "#ERUNMagazine #MotionNoir #AnalogFuturism #Techwear"
  },
  {
    id: "pink-smoke-halo",
    src: "images/erun_issue_pink_smoke_halo_3x4.jpg",
    title: "Pink Smoke Halo — Orbital Bloom",
    collection: "Collection 03 — Minimalist Chrome",
    pillar: "Cyber-Elegance",
    tag: "Issue 09",
    palette: "#FF7BAC",
    masthead: "White Minimalist",
    prompt: "Model with sharp graphic eyeliner, silver liquid-metallic bodysuit, glossy black helium balloons on polished steel rods — clean grey studio, geometric futurism.",
    hook: "Absolute symmetry. Zero compromises. 💎⚫",
    story: "Thermal vacuum-sealed bodysuit without a single stitch — pressurized obsidian spheres celebrate stillness in sensory overload.",
    cta: "Minimal or maximal?",
    hashtags: "#ERUNMagazine #MinimalistFashion #SilverChrome #GeometricDesign"
  },
  {
    id: "petal-time-procession",
    src: "images/erun_issue_petal_time_procession_3x4.jpg",
    title: "Petal Time Procession",
    collection: "Collection 14 — Processional",
    pillar: "Bio-Futurism",
    tag: "Issue 30",
    palette: "#F8E8E8",
    masthead: "Blush Processional",
    prompt: "Slow-motion petal procession gown with cascading fabric petals in pale blush atrium — time-lapse couture.",
    hook: "Time unspooling in petals. 🌸⏳",
    story: "Each petal is a timestamp — gown blooms and wilts on a 24-hour cycle.",
    cta: "Which hour would you wear?",
    hashtags: "#ERUNMagazine #PetalCouture #TimeGown #Processional"
  },
  {
    id: "guts-cinematic",
    src: "images/erun_issue_guts_cinematic.jpg",
    title: "GUTS — Cinematic Brutalism",
    collection: "Collection 02 — Post-Apocalyptic Cyborg",
    pillar: "Neo-Brutalist",
    tag: "Issue 07",
    palette: "#FF1111",
    masthead: "Distressed Red Stencil",
    prompt: "Chrome exoskeleton skull with glowing orange LED eyes, oil-slick iridescent jacket, black turtleneck — post-apocalyptic metal ruins, stormy sky, cinematic contrast.",
    hook: "When the world falls apart, our armor only gets louder. 🦾🔥",
    story: "Salvaged drone titanium and petroleum-cured leathers — facial exoskeleton with thermal sensors and filtration.",
    cta: "Vision or strength upgrade?",
    hashtags: "#ERUNMagazine #CyberpunkFashion #CyborgStyle #IronAndOil"
  },
  {
    id: "mediterranean-analog",
    src: "images/erun_issue_mediterranean_analog.jpg",
    title: "Mediterranean Analog — Solarpunk Atrium",
    collection: "Collection 02 — Solarpunk",
    pillar: "Bio-Futurism",
    tag: "Launch Campaign",
    palette: "#8ECA9A",
    masthead: "Mediterranean",
    prompt: "Sun-drenched Mediterranean atrium with living mycelium emerald gown merging with alien foliage — golden hour spores, Kodak Portra 400.",
    hook: "Beauty that blooms from within. 🌸💡",
    story: "Symbiotic botanical enzymes emit golden-cyan aura at dusk — radiance is no longer metaphor.",
    cta: "Tag someone who illuminates every room.",
    hashtags: "#ERUNMagazine #Solarpunk #MediterraneanFuturism #MyceliumCouture"
  },
  {
    id: "new-mercury",
    src: "images/erun_new_concept_mercury.jpg",
    title: "Acoustic Levitation — Liquid Mercury",
    collection: "New Concept 31 — Acoustic Physics",
    pillar: "New Concepts",
    tag: "NEW CONCEPT",
    palette: "#C0C0C0",
    masthead: "Pristine White",
    prompt: "Matte black silk evening gown in charcoal anechoic chamber, polished mercury spheres levitated by 40kHz acoustic waves orbiting shoulders — Hasselblad crisp studio.",
    hook: "When sound waves sculpt liquid metal. 🔊🫧",
    story: "84 discrete mercury spheres orbit torso, merging into breastplate when frequency shifts — stitching replaced by sound.",
    cta: "What song would shape your dress?",
    hashtags: "#ERUNMagazine #AcousticLevitation #LiquidMercury #PhysicsFashion"
  },
  {
    id: "new-silkmoth",
    src: "images/erun_new_concept_silkmoth.jpg",
    title: "Silk-Moth Dynasty — Aerogel & Gold Silk",
    collection: "New Concept 32 — Bio-Mimicry",
    pillar: "New Concepts",
    tag: "NEW CONCEPT",
    palette: "#E6C77A",
    masthead: "Classic White",
    prompt: "Full-length coat of bioluminescent golden silk and translucent aerogel glowing like fog, chitin moth-scale collar and antennae filigree — misty greenhouse twilight, Kodak Portra.",
    hook: "Engineered from living golden silk and weightless aerogel. 🦋✨",
    story: "Silica aerogel 99.8% air fused with golden silk — 40-gram coat that insulates absolutely. To wear aerogel is to wear frozen fog.",
    cta: "Would you wear frozen fog in winter?",
    hashtags: "#ERUNMagazine #BioMimicry #AerogelFashion #SilkMothCouture"
  },
  {
    id: "new-lightning",
    src: "images/erun_new_concept_lightning.jpg",
    title: "High Voltage — Wearable Tesla Coils",
    collection: "New Concept 33 — Electrostatic",
    pillar: "New Concepts",
    tag: "NEW CONCEPT",
    palette: "#00FFCC",
    masthead: "Electric Cyan",
    prompt: "Structured carbon-fiber trench with copper coils and vacuum tubes, purple-cyan plasma tendrils crackling — dark electrostatic observatory thunderstorm, high contrast.",
    hook: "Harnessing 50,000 volts inside carbon fiber. ⚡🏙️",
    story: "Faraday shielding + copper-wound tubes channel ionization into violet plasma aura — wearer commands the current.",
    cta: "Tag someone who's pure electricity!",
    hashtags: "#ERUNMagazine #TeslaCouture #HighVoltageFashion #StormStyle"
  },
  {
    id: "azborn-greenhouse",
    src: "images/azborn_biofuturism_greenhouse.jpg",
    title: "Xenobotanical Greenhouse — Solarpunk",
    collection: "AZBORN Pillar — Bio-Futurism",
    pillar: "Bio-Futurism",
    tag: "AZBORN",
    palette: "#4CAF7A",
    masthead: "Mediterranean",
    prompt: "Model in living mycelium emerald organza dress merging with alien foliage in solarpunk greenhouse dome — golden hour, bioluminescent amber spores.",
    hook: "Living dress, breathing greenhouse.",
    story: "Mycelium silk organza merges with exotic alien foliage — garment grows with you.",
    hashtags: "#AZBORNMagazine #SolarpunkFashion #BioFuturism #Xenobotany"
  },
  {
    id: "azborn-glitch",
    src: "images/azborn_digitalsurrealism_glitch.jpg",
    title: "Zero-Gravity Glitch Refraction",
    collection: "AZBORN Pillar — Digital Surrealism",
    pillar: "Digital Surrealism",
    tag: "AZBORN",
    palette: "#B794F6",
    masthead: "Digital Surrealism",
    prompt: "Floating model in holographic glitch crystalline dress with pastel lavender liquid-light ribbons orbiting silhouette — chrome spheres, ultraviolet rim lights.",
    hook: "What if gravity wasn't a design constraint? 🔮✨",
    story: "Zero-gravity tailoring becomes architecture — liquid-light ribbons orbit in planetary loops.",
    hashtags: "#AZBORN #GlitchCouture #HolographicFashion #ZeroGravity"
  },
  {
    id: "azborn-techwear",
    src: "images/azborn_neobrutalist_techwear.jpg",
    title: "Urban Utility — Ballistic Nylon",
    collection: "AZBORN Pillar — Neo-Brutalist",
    pillar: "Neo-Brutalist",
    tag: "AZBORN",
    palette: "#FF4500",
    masthead: "Neo-Brutalist",
    prompt: "Avant-garde techwear trench in matte black ballistic nylon with reflective silver panels on wet elevated concrete walkway — neon orange/violet reflections, rain mist.",
    hook: "Luxury means absolute protection. ⛈️🖤",
    story: "Graphene-reinforced ballistic nylon with magnetic closures and thermal dampening — defiance against the elements.",
    cta: "Form over function or ultimate utility?",
    hashtags: "#AZBORN #Techwear #NeoBrutalist #CyberpunkStyle"
  },
  {
    id: "azborn-editorial",
    src: "images/azborn_futuristic_editorial_sample.jpg",
    title: "Translucent Futures — Liquid Light",
    collection: "AZBORN Pillar — Cyber-Elegance",
    pillar: "Cyber-Elegance",
    tag: "AZBORN",
    palette: "#E2E8F0",
    masthead: "Cyber-Elegance",
    prompt: "Cyborg model with chrome facial filigree in translucent liquid-crystal haute couture gown flowing in weightless ribbons — neo-futuristic atrium, cyan panels.",
    hook: "What will luxury look like when fabrics are liquid light? 🌐✨",
    story: "Molecular garments adapt to temperature and emotion — fashion as intimate interface.",
    cta: "Living bio-luminescence or classic textiles?",
    hashtags: "#AZBORNMagazine #LiquidCrystal #CyberElegance #FutureHauteCouture"
  },
  {
    id: "biosynthetic-pearls",
    src: "images/erun_issue_biosynthetic_pearls.jpg",
    title: "Biosynthetic Pearls — Studio Variant",
    collection: "Collection 05 — Biosynthetic",
    pillar: "Bio-Futurism",
    tag: "Issue 12",
    palette: "#EDE9E3",
    masthead: "Pearlescent",
    prompt: "Close studio variant of biosynthetic pearls — amniotic membranes and engineered pearls, soft opalescent lighting.",
    hashtags: "#ERUNMagazine #BiosyntheticPearls #StudioVariant"
  },
  {
    id: "pink-smoke-halo-realism",
    src: "images/erun_issue_pink_smoke_halo_realism_3x4.jpg",
    title: "Pink Smoke Halo — Realism",
    collection: "Collection 03 — Minimalist Chrome",
    pillar: "Cyber-Elegance",
    tag: "Variant",
    palette: "#FFB6D9",
    masthead: "White",
    prompt: "Realism variant — pink smoke halo with chrome bodysuit, softer skin texture, photoreal focus.",
    hashtags: "#ERUNMagazine #PinkSmoke #RealismVariant"
  },
  {
    id: "twilight-reference",
    src: "images/erun_issue_twilight_motion_noir_reference_portrait_3x4.jpg",
    title: "Twilight Reference Portrait — Noir Study",
    collection: "Collection 06 — Reference",
    pillar: "Neo-Brutalist",
    tag: "Reference",
    palette: "#2A2A2A",
    masthead: "Reference",
    prompt: "Reference portrait study for twilight motion noir — analog grain, chiaroscuro, intense gaze.",
    hashtags: "#ERUNMagazine #ReferenceStudy #Portraiture #Noir"
  }
];

export default issues;
